
%%
clear ;
s(1) = GenSamplStruct('Jittered', '') ;
i(1) = GenIntegStruct('Pbrt', ['--epath ' '/home/kartic/pbrt/pbrt-v2/src/bin/pbrt ' '--spath ' '/home/kartic/pbrt/pbrt-v2/scenes/killeroo-simple.pbrt ' ...
                        '--pypath ' '../python/pbrt-cl.py ' '--crop .25 .27 .46 .47 ' '--img ' '../out/test.exr' ]) ;

ns = [2 4 6] ;
nr =  1;
ofile = '../out/test';
binfile = '../build/eea' ;
atype = 'mse' ;

data = CollectConvData(ns, nr, ofile, binfile, s, i, atype) ;
                    
%%

clear; 
%%%%%%%%%%% samplers 
s(1) = GenSamplStruct('Jittered', '') ;
s(2) = GenSamplStruct('Random', '') ;
s(3) = GenSamplStruct('BJittered', '--boxwidth .3') ;
s(4) = GenSamplStruct('BJittered', '--boxwidth .5') ;
s(5) = GenSamplStruct('GJittered', '--sigma .3') ;
s(6) = GenSamplStruct('GJittered', '--sigma .5') ;

%%%%%%%%%%% Integrands
i(1) = GenIntegStruct('QuadPix', ['--points ' num2str(rand(1,4))]) ;
i(2) = GenIntegStruct('PWConstant', '--npts 10 --random') ;
i(3) = GenIntegStruct('PWConstant', '--npts 100 --random') ;
i(4) = GenIntegStruct('PWConstant', '--npts 1000 --random') ;


%%%%%%%%%%% Analysis Parameters
ns = [9 36 100 1024] ;
nr =  50;
ofile = '../out/test';
binfile = '../build/eea' ;
atype = 'var' ;

system (['rm ' ofile '*.txt']) ;
data = CollectConvData(ns, nr, ofile, binfile, s, i, atype) ;


%% Plot data generated by CollectConvData

PlotConvData(data) ;



