

%%
clear ;
s(1) = GenSamplStruct('Jittered', '') ;
s(2) = GenSamplStruct('Random', '') ;

i(1) = GenIntegStruct('Pbrt', ...
            [ '--epath /home/kartic/pbrt/pbrt-v3/pbrt ' ...
            '--spath /home/kartic/pbrt/pbrt-v3-scenes/subusrface-spheres/spheres.pbrt '...
            '--pypath /home/kartic/Projects/FAS2016/code/Analysis/python/pbrt-cl.py '...
            '--crop 0.2 0.21 0.79 0.8 --pbrtstype $$SAMP$$ --refnspp 0 --img pbrt-eea.exr']) ;


ns = [4 16 32 1024] ;
nr =  10;
ofile = '../out/test';
binfile = '../build/eea' ;
atype = 'var' ;

system (['rm ' ofile '*.txt']) ;
data = CollectConvData(ns, nr, ofile, binfile, s, i, atype) ;
%% Plot data generated by CollectConvData

PlotConvData(data) ;


%%

clear; 
%%%%%%%%%%% samplers 
s(1) = GenSamplStruct('Jittered', '') ;
s(2) = GenSamplStruct('Random', '') ;
s(3) = GenSamplStruct('BJittered', '--boxwidth .3') ;
s(4) = GenSamplStruct('BJittered', '--boxwidth .5') ;
s(5) = GenSamplStruct('GJittered', '--sigma .3') ;
s(6) = GenSamplStruct('GJittered', '--sigma .5') ;

%%%%%%%%%%% Integrands
i(1) = GenIntegStruct('QuadPix', ['--points ' num2str(rand(1,4))]) ;
% i(2) = GenIntegStruct('PWConstant', '--npts 10 --random') ;
% i(3) = GenIntegStruct('PWConstant', '--npts 100 --random') ;
% i(4) = GenIntegStruct('PWConstant', '--npts 1000 --random') ;

%%%%%%%%%%% Analysis Parameters
ns = [9 36 100 1024] ;
nr =  50;
ofile = '../out/test';
binfile = '../build/eea' ;
atype = 'var' ;

%%

system (['rm ' ofile '*.txt']) ;
data = CollectConvData(ns, nr, ofile, binfile, s, i, atype) ;


%% Plot data generated by CollectConvData

PlotConvData(data) ;



